# Rustfmt configuration for this project

# Maximum line width
max_width = 100

# Additional formatting options you might want to consider:
# tab_spaces = 4
# hard_tabs = false
# newline_style = "Unix"
# use_small_heuristics = "Default"
# reorder_imports = true
# reorder_modules = true
# remove_nested_parens = true
# edition = "2021"
