[package]
name = "subnet_rental_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11"
serde = "1.0.193"
serde_bytes = "0.11.12"
ic-stable-structures = "0.6.0"
sha2 = "0.10.8"
hex = "0.4.3"

[dev-dependencies]
pocket-ic = "2.0.1"
