[package]
name = "xrc_mock"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
candid = "0.10.1"
ic-cdk = "0.13.1"
serde = "1.0.197"
