[package]
name = "xrc_mock"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
candid = "0.10.14"
ic-cdk = "0.18.4"
serde = "1.0.219"
