[package]
name = "xrc_mock"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.14"
ic-cdk = "0.18.4"
ic-xrc-types = "1.2.0"
serde = "1.0.219"
