[package]
name = "xrc_mock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.10.2"
hex = "0.4.3"
ic-cdk = "0.13.1"
serde = "1.0.197"
serde_bytes = "0.11.14"
